# Generated by Django 3.0.6 on 2023-07-21 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=50)),
                ('brand_name', models.CharField(max_length=100)),
                ('fabric', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=50)),
                ('fitting_type', models.CharField(max_length=50)),
                ('is_imported', models.BooleanField(default=False)),
                ('colors', models.CharField(max_length=200)),
                ('sizes', models.CharField(choices=[('S', 'XS'), ('M', 'L'), ('XL', 'LL')], default='Small', max_length=10)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Category')),
            ],
        ),
    ]
