# Generated by Django 3.0.6 on 2023-07-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sizes',
        ),
        migrations.AddField(
            model_name='category',
            name='sizes',
            field=models.CharField(choices=[('S', 'XS'), ('M', 'L'), ('XL', 'LL')], default='S', max_length=10),
        ),
    ]
